# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Bulild
          command: make build
      - run:
          name: Run tests
          command: |
            mkdir /tmp/artifacts
            go test ./... -race -coverprofile=coverage.txt -covermode=atomic
            cat coverage.txt
            mv coverage.txt /tmp/artifacts
      - store_test_results:
          path: /tmp/artifacts
      - codecov/upload:
          file: /tmp/artifacts/coverage.txt
      - sonarcloud/scan

      - run:
          name: Appened to Report
          command: |
            curl -X GET https://codecov.io/api/pub/gh/james5101/gsd-hello-world/settings?access_token=${CODECOV_API_TOKEN}
            curl -u ${SONARCLOUD_API_TOKEN}: https://sonarcloud.io/api/measures/component

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
